### ISSUE TITLE
Pop-up menu issue with dark theme

### ISSUE THREAD

**Issue by fb82** [JD342/arc-thunderbird-integration#2] opened 2017-04-04 22:50 UTC
Hi,

I like a lot your Thunderbird theme, nice work!

I know theme is still alpha, but I've noted that direct menus popped-up from toolbars button have almost identical text and background colors on dark themes  (see screeshots), is there any way to solve this issue?
 
![1](https://cloud.githubusercontent.com/assets/26028927/24682119/58ded97c-1998-11e7-92d5-504ecc4dd406.png)
![2](https://cloud.githubusercontent.com/assets/26028927/24682120/58e0d1aa-1998-11e7-93be-c690547ccd42.png)

**Comment by ghost** [comment] 2017-04-05 09:24
Dark theme support does in need of improvement but the regular Arc theme looks really nice now with 0.3! Great job so far, thank you!

EDIT: Also the contacts window seems to be unaffected by the the theme for me.

**Comment by nicolafio** [comment] 2017-04-05 17:02
@fb82 Thanks for letting me know. At the moment the dark and darker themes do not fare well with the integration. You may want to switch to the light theme. Otherwise you can try to force Thunderbird to use the light theme by opening the destkop entry file with super user pemissions at `/usr/share/applications/thunderbird.desktop` and replacing the line from `Exec=/usr/bin/thunderbird %u` to 
`Exec=env GTK2_RC_FILES=/usr/share/themes/Arc/gtk-2.0/gtkrc /usr/bin/thunderbird %u`. Note that `GTK2_RC_FILES` is an experimental environment variable and may not work as intended.

@szekeres2016 The integration currently restyles the main window. It is possible to restyle the other windows as well, but inspecting and working with them is a pain in the butt. I will eventually attempt to handle them in the future, when I get to know how everything works.

**Comment by fb82** [comment] 2017-04-06 07:10
It works, thank you again!


Il 05/04/2017 19:02, JD342 ha scritto:

**Comment by nicolafio** [comment] 2017-06-12 09:57
@fb82 The issue with pop-up menus should be fixed in the version 0.4.0.
@szekeres2016 If by contacts window you mean the address book, version 0.4.0 now applies styling on it.

**Closed as completed by nicolafio** 2017-06-12 09:57 UTC
