### ISSUE TITLE
Arc Integration is missing on panel display in preference

### ISSUE THREAD

**Issue by dagoll** [JD342/arc-thunderbird-integration#7] opened 2017-07-06 07:40 UTC
Hello JD,

I want to report on update v0.4.3, **Arc Integration** option missing on display panel in preference.
I'm using thunderbird v52.2.1

Please to be fixed, thanks.

**Comment by jplatte** [comment] 2017-07-06 08:05
Seems like the same problem I've been having, see #5. Try clicking around in Thunderbird, then going to the preferences again and see if the Arc Integration settings are there.

**Comment by nicolafio** [comment] 2017-07-06 09:37
@dagoll Thank you for reporting this bug. I have not yet been able to reproduce it on my system. I will need to search further.

I am closing this issue as it seems to be a duplicate. If you want to add further comments on this problem, fell free to do it on issue #5. Thank you again for your time.

**Closed as completed by nicolafio** 2017-07-06 09:37 UTC
Labels: duplicate
